reporting: "on"
startuppopupversion: 1
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --line-numbers --side-by-side
gui:
  showCommandLog: true
  showFileTree: true
